[package]
name = "netf"
version = "0.1.0"
authors = ["PostRex <post-rex@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
regex = "1.3.3"
byteorder = "1.3.2"
